apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.68.247"],"port":31000,"protocol":"TCP","serviceName":"default:my-webapp-service","allNodes":true}]
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"my-webapp-service","namespace":"default"},"spec":{"ports":[{"nodePort":31000,"port":8080,"protocol":"TCP","targetPort":80}],"selector":{"app":"my-webapp"},"type":"NodePort"}}
  creationTimestamp: '2025-03-11T23:40:09Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
      manager: agent
      operation: Update
      time: '2025-03-11T23:40:09Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2025-03-11T23:40:09Z'
  name: my-webapp-service
  namespace: default
  resourceVersion: '11182'
  uid: c15255fe-9271-477e-9663-3e04538e8830
spec:
  clusterIP: 10.43.4.69
  clusterIPs:
    - 10.43.4.69
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31000
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: my-webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
